language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - 4.0
  - 4.1
  - 4.2
  - iojs
  - iojs-v1.0.4

os:
  - linux

before_script:
  - export yandexMapApiKey='ALTJHk8BAAAAREWTEg=='
  
notifications:
  email: false
  
